### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by millette** [sindresorhus/gh-user#1]
You beat me to it for gh-got, but I'm adding the promise interface to gh-user right now. Hope that's ok :-)

**Comment by sindresorhus** [comment]
:+1: Go ahead :)

And if you're bored, here are some more modules that could use promisification: https://www.npmjs.com/browse/depended/gh-got

**Comment by millette** [comment]
I'm not actually bored, thanks :-) But I am working hard to find the time (see what I did there) to release the tools and a site with local (Québec) githubbers, just in time for the Semaine québécoise de l'informatique libre beginning in 10 days. I will try to fix modules as I need them. Thanks for the pointer.
