### ISSUE TITLE
Not working as documented

### ISSUE THREAD

**Issue by seriema** [sindresorhus/gh-user#4]
The version I get from npm doesn't seem to match the repository, even though both say it's version 1.0.0. There's no `then()` to use, and the main method is expecting a callback.

Here's the source I got from npm:

````
'use strict';
var ghGot = require('gh-got');

module.exports = function (username, token, cb) {
	if (typeof username !== 'string') {
		throw new Error('`username` required');
	}

	if (typeof token === 'function') {
		cb = token;
		token = null;
	}

	ghGot('users/' + username, {
		token: token,
		headers: {
			'user-agent': 'https://github.com/sindresorhus/gh-user'
		}
	}, function (err, data) {
		if (err && err.code === 404) {
			cb(new Error('User `' + username + '` doesn\'t exist'));
			return;
		}

		if (err) {
			cb(err);
			return;
		}

		// remove deprecated props
		delete data.gravatar_id;
		delete data.bio;

		cb(null, data);
	});
};
````

This is what I'm seeing in this repo (master):

````
'use strict';
var ghGot = require('gh-got');
var Promise = require('pinkie-promise');

module.exports = function (username, token) {
	if (typeof username !== 'string' || !username) {
		return Promise.reject(new Error('`username` required'));
	}

	return ghGot('users/' + username, {
		token: token,
		headers: {
			'user-agent': 'https://github.com/sindresorhus/gh-user'
		}
	}).then(function (result) {
		delete result.body.gravatar_id;
		delete result.body.bio;
		return result.body;
	});
};
````

**Comment by arthurvr** [comment]
The version on master simply isn't released yet. The last release is 1.0 and didn't contain the promisification yet.

**Comment by seriema** [comment]
Well the `package.json` on master says 1.0.0. Maybe do these changes in a branch before publishing? The doc still doesn't match what I'm downloading so I'll stick with my bug title =)

**Comment by sindresorhus** [comment]
Master is dev. That's how most node modules are developed. For specific releases see the readme in the tagged releases or on npm.

**Comment by seriema** [comment]
I could argue that I've never seen that and that the Github Workflow that most projects on GH follow always has the relases on Master, but since you own most of the packages on npm you're correct by definition. :joy:

**Comment by nexdrew** [comment]
@sindresorhus Don't mean to be a troll, but are there any plans to release the next version with promises? :grinning: I assume it will be `2.0.0` unless master is refactored to support both callbacks and promises (similar to `got`)? Anything I can do to help?

//cc @arthurvr

**Comment by sindresorhus** [comment]
I'm sure I did, but the publish must have failed somehow. Since publishing usually takes 20 seconds, sometimes I tab away from it, and forget to go back and confirmed it succeeded. Published now.

**Comment by nexdrew** [comment]
Awesome, thanks!
